name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        #ssh-keyscan -p ${{ secrets.VPS_PORT || '22' }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        #ssh-keyscan -p 9273 v2.iifoundation.site >> ~/.ssh/known_hosts
        echo "178.157.82.235:9273 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGXLsElwytfEcy1Gw48YGoLCARGyuuSD9tBcS85r9y1S" >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh -p ${{ secrets.VPS_PORT || '22' }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/public_html/app
          if [ ! -d .git ]; then
            git clone git@github.com:asgharmughal/v2demosite.git .
          else
            git pull origin main
          fi
          # git pull origin main
          # Restart service or app (e.g., PM2, systemd, docker, etc.)
          # e.g., pm2 restart my-app
        EOF
